version: "3"
services:
  krakend:
    image: krakend_image
    build:
      context: ./
      dockerfile: .
    volumes:
      - krakend_data:/krakend
    ports:
      - 4502:8080
      - 8099:8099
    container_name: krakend_api_gateway

volumes:
  krakend_data:
    external: true